from django.conf.urls import url
from views import (
    index,
    PostListView,
    post_detail,
    UserProfileView,
    UserProfileRelationsView,
    comment_create,
    post_edit,
    post_delete,
    accept_friend_request,
    reject_friend_request,
    cancel_friend_request,
    UnfriendView,
    CommentCreateView,
    CommentEditView,
    CommentDeleteView,
    PostCreateView,
    PostEditView,
    PostDeleteView,
    AcceptFriendRequestView,
    SendFriendRequestView,
    UserProfileUpdateView,
    RegisterView,
    LoginView,
)

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^$', PostListView.as_view(), name='post_list'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^post/(?P<pk>[0-9]+)$', post_detail, name='post_detail'),
    url(r'^post/create$', PostCreateView.as_view(), name='post_create'),
    # url(r'^post/(?P<pk>[0-9]+)/edit$', post_edit, name='post_edit'),
    url(r'^post/(?P<pk>[0-9]+)/edit$', PostEditView.as_view(), name='post_edit'),
    # url(r'^post/(?P<pk>[0-9]+)/delete$', post_delete, name='post_delete'),
    url(r'^post/(?P<pk>[0-9]+)/delete$', PostDeleteView.as_view(), name='post_delete'),
    # url(r'^post/(?P<pk>[0-9]+)/comment/create$', comment_create, name='comment_create'),
    url(r'^post/(?P<pk>[0-9]+)/comment/create$', CommentCreateView.as_view(), name='comment_create'),
    url(r'^post/(?P<pk>[0-9]+)/comment/(?P<pk_comment>[0-9]+)/edit$', CommentEditView.as_view(), name='comment_edit'),
    url(r'^post/(?P<pk>[0-9]+)/comment/(?P<pk_comment>[0-9]+)/delete$', CommentDeleteView.as_view(), name='comment_delete'),
    url(r'^userprofile/(?P<pk>[0-9]+)$', UserProfileView.as_view(),
        name='user_profile'),
    url(r'^userprofile/(?P<pk>[0-9]+)/relations$', UserProfileRelationsView.as_view(),
        name='user_profile_relations'),
    url(r'^userprofile/(?P<pk>[0-9]+)/edit$', UserProfileUpdateView.as_view(),
        name='profile_edit'),
    # url(r'^accept_friend_request/(?P<user_pk>[0-9]+)$', accept_friend_request,
    #     name='accept_friend_request'),
    url(r'^accept_friend_request/(?P<user_pk>[0-9]+)$', AcceptFriendRequestView.as_view(),
        name='accept_friend_request'),
    url(r'^reject_friend_request/(?P<user_pk>[0-9]+)$', reject_friend_request,
        name='reject_friend_request'),
    url(r'^cancel_friend_request/(?P<user_pk>[0-9]+)$', cancel_friend_request,
        name='cancel_friend_request'),
    url(r'^unfriend/(?P<friend_pk>[0-9]+)$', UnfriendView.as_view(),
        name='unfriend'),
    url(r'^send_friend_request/(?P<user_pk>[0-9]+)$', SendFriendRequestView.as_view(),
        name='send_friend_request'),
]
